language: node_js

env:
- CODECOV_TOKEN="a0269be2-ef59-41a9-8143-d23759b3304e"
- CODACY_PROJECT_TOKEN="65ac6922ade949b09d503b5b651fe4b8"

node_js:
  - "7"
  - "6"
  - "5"
  - "4"

after_success:
  - npm run coverage
  - codecov
  - cat ./coverage/lcov.info | coveralls
  - bash <(curl -s https://codecov.io/bash)
  - ./node_modules/.bin/codacy-coverage.