language: node_js

env:
- CODECOV_TOKEN="f9c8c2d0-359e-4f13-bc90-bcc2b3889683"

node_js:
  - "7"
  - "6"
  - "5"
  - "4"

after_success:
  - npm run coverage
  - codecov
  - cat ./coverage/lcov.info | coveralls
  - bash <(curl -s https://codecov.io/bash)